#!/usr/bin/env python3
import requests
import time
import sys
import os
from concurrent.futures import ThreadPoolExecutor

# Configuration
MIRROR_STATUS_URL = "https://archlinux.org/mirrors/status/json/"
TARGET_FILE = "/etc/pacman.d/mirrorlist"
MAX_MIRRORS = 10  # Number of mirrors to save
TIMEOUT = 3       # Seconds to wait per mirror

def test_mirror(mirror):
    url = mirror['url']
    try:
        start = time.time()
        # We perform a HEAD request to check latency without downloading the full DB
        response = requests.head(url, timeout=TIMEOUT)
        if response.status_code == 200:
            return (time.time() - start, url)
    except:
        pass
    return (float('inf'), url)

def main():
    if os.geteuid() != 0:
        print("Error: This script must be run as root to write to /etc/pacman.d/mirrorlist")
        sys.exit(1)

    print("Fetching mirror list from archlinux.org...")
    try:
        data = requests.get(MIRROR_STATUS_URL).json()
    except Exception as e:
        print(f"Failed to fetch mirror list: {e}")
        sys.exit(1)

    # Filter for HTTPS and up-to-date mirrors
    mirrors = [m for m in data['urls'] if m['protocol'] == 'https' and m['active']]
    
    print(f"Testing {len(mirrors)} mirrors...")
    results = []
    with ThreadPoolExecutor(max_workers=20) as executor:
        results = list(executor.map(test_mirror, mirrors))

    # Sort by latency and pick the best
    results.sort(key=lambda x: x[0])
    fastest = [r[1] for r in results if r[0] < float('inf')][:MAX_MIRRORS]

    if not fastest:
        print("No reachable mirrors found.")
        sys.exit(1)

    print(f"Found {len(fastest)} fast mirrors. Applying...")
    
    with open(TARGET_FILE, 'w') as f:
        f.write("## Generated by fastmirror tool\n")
        for url in fastest:
            f.write(f"Server = {url}$repo/os/$arch\n")

    print(f"Successfully updated {TARGET_FILE}")

if __name__ == "__main__":
    main()
